### ISSUE TITLE
Planet Selection Non-Functional

### ISSUE THREAD

**Issue by agm-114** [Conquer-Space/Conquer-Space#153]
Planet selection for non-gas giants is currently non-functional.
If you click on mercury, venus, or the earth the camera focuses on the sun for some reason.

In addition, the planet viewer does not currently display the currently selected planet.

**Comment by agm-114** [comment]
In addition, the planet viewer does not currently display the currently selected planet.

**Comment by EhWhoAmI** [comment]
Fixed with #168
